# ============================================================
# 1wellness Deep Cleanup — Pass 2
# ============================================================
$base = "c:\Users\Alex\TraeCoder\1wellness"

function Swap {
    param([string]$FilePath, [string[][]]$Pairs)
    if (-not (Test-Path $FilePath)) { return }
    $c = [System.IO.File]::ReadAllText($FilePath, [System.Text.Encoding]::UTF8)
    $changed = $false
    foreach ($p in $Pairs) {
        if ($c.Contains($p[0])) { $c = $c.Replace($p[0], $p[1]); $changed = $true }
    }
    if ($changed) {
        [System.IO.File]::WriteAllText($FilePath, $c, [System.Text.Encoding]::UTF8)
        Write-Host "OK: $FilePath" -ForegroundColor Green
    }
}

# ── JS files ─────────────────────────────────────────────────
$jsPairs = @(
    @("OJG Herbal Sales Pages",       "1wellness Sales Pages"),
    @("OJG Herbal",                   "1wellness"),
    @("OJG PCOS program",             "1wellness CycleSync program"),
    @("OJG_",                         "1W_"),
    @("OJG Herbal Plan Renewal",      "1wellness Plan Renewal"),
    @("ojg-herbal-website",           "1wellness-website"),
    @("ojg_currency_preference",      "1w_currency_preference"),
    @("ojg_new_user_creds",           "1w_new_user_creds"),
    @("ojg_auto_login",               "1w_auto_login"),
    @("ojg_session_id",               "1w_session_id"),
    @("ojg_nurture_",                 "1w_nurture_"),
    @("ojg_purchased",                "1w_purchased"),
    @("ojg_pcos_type",                "1w_pcos_type"),
    @("ojg_acne_type",                "1w_acne_type"),
    @("ojg_weight_type",              "1w_weight_type"),
    @("ojg_",                         "1w_"),
    @("'ojg_",                        "'1w_")
)
Swap -FilePath "$base\js\data-manager.js"              -Pairs $jsPairs
Swap -FilePath "$base\js\flutterwave-integration.js"   -Pairs $jsPairs
Swap -FilePath "$base\js\webhook-manager.js"           -Pairs $jsPairs

# ── Member JS ─────────────────────────────────────────────────
Swap -FilePath "$base\member\js\dashboard-enhanced.js" -Pairs $jsPairs
Swap -FilePath "$base\member\js\dashboard.js"          -Pairs $jsPairs

# ── Member PHP components ─────────────────────────────────────
$memberComponents = @("dashboard_view.php","header.php","modals.php","nourish_view.php","profile_view.php","sidebar.php","tracker_view.php","weekly_view.php")
$phpPairs = @(
    @("OJG Herbal Member",  "1wellness Member"),
    @("OJG Herbal",         "1wellness"),
    @("OJG PCOS program",   "1wellness CycleSync program")
)
foreach ($f in $memberComponents) {
    Swap -FilePath "$base\member\components\$f" -Pairs $phpPairs
}

# ── Member index.html & member index.php ─────────────────────
$memberHtmlPairs = @(
    @("OJG PCOS program",             "1wellness CycleSync program"),
    @("OJG_",                         "1W_"),
    @("OJG Herbal Plan Renewal",      "1wellness Plan Renewal"),
    @("ojg_pcos_type",                "1w_pcos_type"),
    @("ojg.",                         "1wellness.")
)
Swap -FilePath "$base\member\index.html"  -Pairs $memberHtmlPairs
Swap -FilePath "$base\member\index.php"   -Pairs (@(@("OJG Herbal Member", "1wellness Member"), @("OJG Herbal", "1wellness")))
Swap -FilePath "$base\member\login.html"  -Pairs (@(@("ojg.", "1wellness."), @("OJG", "1wellness")))
Swap -FilePath "$base\member\login.php"   -Pairs (@(@("ojg.", "1wellness."), @("OJG", "1wellness")))
Swap -FilePath "$base\member\print_plan.php" -Pairs (@(@("OJG Herbal", "1wellness"), @("OJG", "1wellness")))

# ── Backend index.php (admin) ─────────────────────────────────
$adminPairs = @(
    @("ojg.", "1wellness."),
    @("OJG", "1wellness")
)
Swap -FilePath "$base\backend\index.php"         -Pairs $adminPairs
Swap -FilePath "$base\backend\admin\index.php"   -Pairs $adminPairs
Swap -FilePath "$base\backend\admin\login.php"   -Pairs $adminPairs
Swap -FilePath "$base\backend\admin\nav.php"     -Pairs $adminPairs

# ── Plan template ─────────────────────────────────────────────
$templatePairs = @(
    @("Generated by OJG Herbal AI", "Generated by 1wellness AI"),
    @("OJG Herbal AI",              "1wellness AI"),
    @("OJG Herbal",                 "1wellness"),
    @("OJG",                        "1wellness")
)
$tFiles = Get-ChildItem -Path "$base\backend\templates" -Recurse -Include "*.html" -ErrorAction SilentlyContinue
foreach ($tf in $tFiles) {
    Swap -FilePath $tf.FullName -Pairs $templatePairs
}

# ── docs.html ─────────────────────────────────────────────────
Swap -FilePath "$base\backend\docs.html" -Pairs (@(
    @("OJG Herbal API Documentation", "1wellness API Documentation"),
    @("OJG Herbal API",               "1wellness API"),
    @("OJG Herbal",                   "1wellness"),
    @("OJG",                          "1wellness")
))

# ── reset_admin_password.php ─────────────────────────────────
Swap -FilePath "$base\backend\reset_admin_password.php" -Pairs @(
    @("ojgherbal.sqlite", "1wellness.sqlite")
)

# ── 88db_config.php and db_config.php — LEAVE CREDENTIALS INTACT
#    (database names like qjixoiuxhk_ojgherbal are server-assigned — do not rename)
Write-Host "SKIP: db_config files — DB credentials left unchanged (server-assigned names)" -ForegroundColor Yellow

# ── Final count ───────────────────────────────────────────────
Write-Host ""
Write-Host "--- Final OJG reference count ---" -ForegroundColor Yellow
$remaining = Get-ChildItem -Path $base -Recurse -Include "*.html","*.php","*.js" |
    Select-String -Pattern "OJG|ojg-wellness|ojgherbal\.com|ojg\.ng|@ojg" |
    Where-Object { $_.Filename -notmatch "db_config|88db_config|rebrand|cleanup" }

Write-Host "$($remaining.Count) references remain (excluding credentials files)" -ForegroundColor Cyan
$remaining | ForEach-Object {
    $fn = $_.Filename; $ln = $_.LineNumber
    Write-Host "  ${fn}:${ln}" -ForegroundColor Gray
}
Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Deep Cleanup COMPLETE" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
