<?php
/**
 * ModuleManifest — defines which modules each condition's plan includes.
 *
 * This is the mechanism that ensures "no workout for acne" and other
 * condition-specific module inclusion/exclusion rules.
 *
 * Modules not listed in a condition's manifest are:
 * - Never generated by the AI
 * - Never rendered in the PDF
 * - Never tracked in the member area
 */
class ModuleManifest
{
    /**
     * All possible modules in the system.
     */
    public const MODULE_MEAL_PLAN = 'meal_plan';
    public const MODULE_MOVEMENT = 'movement';
    public const MODULE_SKINCARE_ROUTINE = 'skincare_routine';
    public const MODULE_HERBAL_PROTOCOL = 'herbal_protocol';
    public const MODULE_SUPPLEMENTS = 'supplements';
    public const MODULE_CYCLE_SYNC = 'cycle_sync';
    public const MODULE_SLEEP_STRESS = 'sleep_stress';
    public const MODULE_DAILY_LOGGING = 'daily_logging';
    public const MODULE_PROGRESS_VIZ = 'progress_visualization';
    public const MODULE_PHOTO_PROTOCOL = 'photo_protocol';
    public const MODULE_TRIGGER_PROTOCOL = 'trigger_protocol';
    public const MODULE_PLATEAU_PROTOCOL = 'plateau_protocol';
    public const MODULE_RECOVERY_PROTOCOL = 'recovery_protocol';
    public const MODULE_VITALITY_SCORING = 'vitality_scoring';

    /**
     * Module definitions with metadata.
     */
    private const MODULE_DEFS = [
        self::MODULE_MEAL_PLAN => [
            'label' => 'Personalized Meal Plan',
            'description' => 'Localized, condition-specific nutrition plan',
            'required_for_all' => false,
        ],
        self::MODULE_MOVEMENT => [
            'label' => 'Movement & Exercise Protocol',
            'description' => 'Progressive exercise plan appropriate to condition',
            'required_for_all' => false,
        ],
        self::MODULE_SKINCARE_ROUTINE => [
            'label' => 'AM/PM Skincare Routine',
            'description' => 'Topical skincare protocol with specific ingredients',
            'required_for_all' => false,
        ],
        self::MODULE_HERBAL_PROTOCOL => [
            'label' => 'Herbal Protocol',
            'description' => 'Localized herbs with safety gating',
            'required_for_all' => true,
        ],
        self::MODULE_SUPPLEMENTS => [
            'label' => 'Supplement Protocol',
            'description' => 'Evidence-based supplements',
            'required_for_all' => true,
        ],
        self::MODULE_CYCLE_SYNC => [
            'label' => 'Cycle/Phase Synchronization',
            'description' => 'Menstrual cycle-aware protocol',
            'required_for_all' => false,
        ],
        self::MODULE_SLEEP_STRESS => [
            'label' => 'Sleep & Stress Protocol',
            'description' => 'Cortisol management and sleep optimization',
            'required_for_all' => true,
        ],
        self::MODULE_DAILY_LOGGING => [
            'label' => 'Daily Tracking Protocol',
            'description' => 'Condition-specific logging guidance',
            'required_for_all' => true,
        ],
        self::MODULE_PROGRESS_VIZ => [
            'label' => 'Progress Visualization',
            'description' => 'Charts and metrics for tracking progress',
            'required_for_all' => true,
        ],
        self::MODULE_PHOTO_PROTOCOL => [
            'label' => 'Photo Documentation Protocol',
            'description' => 'Baseline and progress photo guidance',
            'required_for_all' => false,
        ],
        self::MODULE_TRIGGER_PROTOCOL => [
            'label' => 'Trigger Identification Protocol',
            'description' => 'Identify and eliminate triggers',
            'required_for_all' => false,
        ],
        self::MODULE_PLATEAU_PROTOCOL => [
            'label' => 'Plateau Response Protocol',
            'description' => 'What to do when progress stalls',
            'required_for_all' => false,
        ],
        self::MODULE_RECOVERY_PROTOCOL => [
            'label' => 'Recovery Protocol',
            'description' => 'Post-exercise and stress recovery',
            'required_for_all' => false,
        ],
        self::MODULE_VITALITY_SCORING => [
            'label' => 'Vitality Scoring',
            'description' => 'Energy and vitality metrics',
            'required_for_all' => false,
        ],
    ];

    /**
     * Module manifest per condition.
     * Only modules listed here will be generated/rendered/tracked.
     */
    private const CONDITION_MANIFESTS = [
        'pcos' => [
            self::MODULE_MEAL_PLAN,
            self::MODULE_MOVEMENT,
            self::MODULE_HERBAL_PROTOCOL,
            self::MODULE_SUPPLEMENTS,
            self::MODULE_CYCLE_SYNC,
            self::MODULE_SLEEP_STRESS,
            self::MODULE_DAILY_LOGGING,
            self::MODULE_PROGRESS_VIZ,
        ],
        'acne' => [
            self::MODULE_MEAL_PLAN,
                // NO movement module for acne
            self::MODULE_SKINCARE_ROUTINE,
            self::MODULE_HERBAL_PROTOCOL,
            self::MODULE_SUPPLEMENTS,
                // Cycle sync only if hormonal acne + female
            self::MODULE_SLEEP_STRESS,
            self::MODULE_DAILY_LOGGING,
            self::MODULE_PROGRESS_VIZ,
            self::MODULE_PHOTO_PROTOCOL,
            self::MODULE_TRIGGER_PROTOCOL,
        ],
        'weight' => [
            self::MODULE_MEAL_PLAN,
            self::MODULE_MOVEMENT, // Core, progressive
            self::MODULE_HERBAL_PROTOCOL,
            self::MODULE_SUPPLEMENTS,
            self::MODULE_SLEEP_STRESS,
            self::MODULE_DAILY_LOGGING,
            self::MODULE_PROGRESS_VIZ,
            self::MODULE_PLATEAU_PROTOCOL,
        ],
        'mens' => [
            self::MODULE_MEAL_PLAN,
            self::MODULE_MOVEMENT, // Strength/recovery
            self::MODULE_HERBAL_PROTOCOL,
            self::MODULE_SUPPLEMENTS,
            self::MODULE_SLEEP_STRESS, // Core for men's
            self::MODULE_DAILY_LOGGING,
            self::MODULE_PROGRESS_VIZ,
            self::MODULE_RECOVERY_PROTOCOL,
            self::MODULE_VITALITY_SCORING,
        ],
    ];

    /**
     * Get the modules for a condition.
     *
     * @param string $condition pcos|acne|weight|mens
     * @return array List of module keys
     */
    public function getModules(string $condition): array
    {
        $condition = strtolower(trim($condition));
        return self::CONDITION_MANIFESTS[$condition] ?? [];
    }

    /**
     * Static alias for getModules
     */
    public static function getModulesStatic(string $condition): array
    {
        $condition = strtolower(trim($condition));
        return self::CONDITION_MANIFESTS[$condition] ?? [];
    }

    /**
     * Get required modules for a condition (core modules that must be present)
     */
    public function getRequiredModules(string $condition): array
    {
        $required = [
            'pcos' => ['meal_plan', 'herbal_protocol', 'supplements', 'cycle_sync', 'sleep_stress', 'tracking'],
            'acne' => ['meal_plan', 'skincare_routine', 'herbal_protocol', 'supplements', 'sleep_stress', 'tracking'],
            'weight' => ['meal_plan', 'movement', 'herbal_protocol', 'supplements', 'sleep_stress', 'tracking'],
            'mens' => ['meal_plan', 'movement', 'herbal_protocol', 'supplements', 'sleep_stress', 'tracking']
        ];

        return $required[$condition] ?? [];
    }

    /**
     * Get forbidden modules for a condition (modules that must NOT be present)
     */
    public function getForbiddenModules(string $condition): array
    {
        $forbidden = [
            'pcos' => ['skincare_routine'],
            'acne' => ['movement'],  // No workout for acne
            'weight' => ['skincare_routine'],
            'mens' => ['skincare_routine', 'cycle_sync']
        ];

        return $forbidden[$condition] ?? [];
    }

    /**
     * Get module definition/metadata.
     */
    public static function getModuleDef(string $module): array
    {
        return self::MODULE_DEFS[$module] ?? [
            'label' => $module,
            'description' => '',
            'required_for_all' => false,
        ];
    }

    /**
     * Get all module definitions.
     */
    public static function getAllModuleDefs(): array
    {
        return self::MODULE_DEFS;
    }

    /**
     * Get all valid condition keys.
     */
    public static function getValidConditions(): array
    {
        return array_keys(self::CONDITION_MANIFESTS);
    }

    /**
     * Validate that a condition is valid.
     */
    public static function isValidCondition(string $condition): bool
    {
        return in_array(strtolower(trim($condition)), self::getValidConditions(), true);
    }

    /**
     * Get condition-specific cycle sync rules.
     * Acne: only if hormonal + female
     * PCOS: always core
     * Others: never
     */
    public static function shouldIncludeCycleSync(string $condition, array $assessment = []): bool
    {
        if ($condition === 'pcos') {
            return true;
        }

        if ($condition === 'acne') {
            $acneType = strtolower($assessment['acne_type'] ?? $assessment['acneType'] ?? '');
            $gender = strtolower($assessment['gender'] ?? '');
            // Only include for hormonal acne in females
            return (strpos($acneType, 'hormonal') !== false) && ($gender === 'female' || $gender === 'f');
        }

        return false;
    }

    /**
     * Get the default tracking keys for a condition.
     * These are wired to the member area logging modules.
     */
    public static function getDefaultTrackingKeys(string $condition): array
    {
        $tracking = [
            'pcos' => [
                ['key' => 'cycle_day', 'label' => 'Cycle Day', 'type' => 'number', 'frequency' => 'daily', 'chart' => 'trend'],
                ['key' => 'mood', 'label' => 'Mood (1-10)', 'type' => 'scale', 'frequency' => 'daily', 'chart' => 'trend'],
                ['key' => 'energy', 'label' => 'Energy Level (1-10)', 'type' => 'scale', 'frequency' => 'daily', 'chart' => 'trend'],
                ['key' => 'cravings', 'label' => 'Cravings', 'type' => 'boolean', 'frequency' => 'daily', 'chart' => 'streak'],
                ['key' => 'symptom_flare', 'label' => 'Symptom Flare', 'type' => 'boolean', 'frequency' => 'daily', 'chart' => 'streak'],
                ['key' => 'weight', 'label' => 'Weight', 'type' => 'number', 'frequency' => 'weekly', 'chart' => 'trend'],
            ],
            'acne' => [
                ['key' => 'skin_photo', 'label' => 'Skin Photo', 'type' => 'photo', 'frequency' => 'daily', 'chart' => 'none'],
                ['key' => 'skin_clarity', 'label' => 'Skin Clarity (1-10)', 'type' => 'scale', 'frequency' => 'daily', 'chart' => 'trend'],
                ['key' => 'flare_count', 'label' => 'New Breakouts', 'type' => 'number', 'frequency' => 'daily', 'chart' => 'trend'],
                ['key' => 'trigger_dairy', 'label' => 'Dairy Today', 'type' => 'boolean', 'frequency' => 'daily', 'chart' => 'streak'],
                ['key' => 'trigger_sugar', 'label' => 'High Sugar Today', 'type' => 'boolean', 'frequency' => 'daily', 'chart' => 'streak'],
                ['key' => 'trigger_sleep', 'label' => 'Poor Sleep (<7h)', 'type' => 'boolean', 'frequency' => 'daily', 'chart' => 'streak'],
                ['key' => 'trigger_stress', 'label' => 'High Stress Day', 'type' => 'boolean', 'frequency' => 'daily', 'chart' => 'streak'],
                ['key' => 'mood', 'label' => 'Mood (1-10)', 'type' => 'scale', 'frequency' => 'daily', 'chart' => 'trend'],
            ],
            'weight' => [
                ['key' => 'weight', 'label' => 'Weight', 'type' => 'number', 'frequency' => 'daily', 'chart' => 'trend'],
                ['key' => 'measurements', 'label' => 'Body Measurements', 'type' => 'number', 'frequency' => 'weekly', 'chart' => 'trend'],
                ['key' => 'energy', 'label' => 'Energy Level (1-10)', 'type' => 'scale', 'frequency' => 'daily', 'chart' => 'trend'],
                ['key' => 'habits_completed', 'label' => 'Habits Completed', 'type' => 'number', 'frequency' => 'daily', 'chart' => 'streak'],
                ['key' => 'nsv_note', 'label' => 'Non-Scale Victory', 'type' => 'text', 'frequency' => 'daily', 'chart' => 'none'],
            ],
            'mens' => [
                ['key' => 'energy', 'label' => 'Energy (1-10)', 'type' => 'scale', 'frequency' => 'daily', 'chart' => 'trend'],
                ['key' => 'libido', 'label' => 'Libido (1-10)', 'type' => 'scale', 'frequency' => 'daily', 'chart' => 'trend'],
                ['key' => 'focus', 'label' => 'Mental Focus (1-10)', 'type' => 'scale', 'frequency' => 'daily', 'chart' => 'trend'],
                ['key' => 'sleep_hours', 'label' => 'Sleep Hours', 'type' => 'number', 'frequency' => 'daily', 'chart' => 'trend'],
                ['key' => 'sleep_quality', 'label' => 'Sleep Quality (1-10)', 'type' => 'scale', 'frequency' => 'daily', 'chart' => 'trend'],
                ['key' => 'strength_session', 'label' => 'Strength Session Done', 'type' => 'boolean', 'frequency' => 'daily', 'chart' => 'streak'],
                ['key' => 'mood', 'label' => 'Mood (1-10)', 'type' => 'scale', 'frequency' => 'daily', 'chart' => 'trend'],
            ],
        ];

        return $tracking[$condition] ?? [];
    }
}